---
config:
  name: rst
  vars:
    -
      name: SIGINIT
      type: ints
      value: 0
    -
      name: SIG
      type: strings
      value: rst
    -
      name: TOGGLEINITDELAY
      type: ints
      value: 10
---
config:
  name: clk
  vars:
    -
      name: SIGINIT
      type: ints
      value: 0
    -
      name: SIG
      type: strings
      value: clk
    -
      name: TOGGLEFOREVER
      type: bool
      value: 1
    -
      name: TOGGLEINITDELAY
      type: ints
      value: 5
    -
      name: TOGGLEDELAY
      type: ints
      value: 5