---
config:
  name: driver
  vars:
    -
      name: SIG
      type: strings
      value: i_bit32Signal1
    -
      name: CLK
      type: strings
      value: clk
---
config:
  name: dataGen
  vars:
    -
      name: REPEAT
      type: ints
      value: 10